# Generated by Django 3.0.7 on 2021-06-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firehydrant',
            name='sys_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='meterinduk',
            name='sys_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pipa',
            name='id_symbol',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pipa',
            name='sys_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pmp',
            name='sys_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='premise',
            name='sys_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pump',
            name='diameter',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pump',
            name='head',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pump',
            name='kecepatan',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pump',
            name='sys_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pump',
            name='voltase',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sipon',
            name='sys_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='titikbocor',
            name='sys_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='valve',
            name='sys_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='washout',
            name='sys_id',
            field=models.IntegerField(null=True),
        ),
    ]
