# Generated by Django 3.0.7 on 2021-06-01 09:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelurahan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, null=True)),
                ('kode', models.CharField(max_length=255, null=True)),
                ('modify_by', models.CharField(max_length=255, null=True)),
                ('modify_date', models.DateTimeField(null=True)),
                ('keterangan', models.CharField(max_length=255, null=True)),
                ('sys_id', models.IntegerField(null=True)),
                ('flag', models.IntegerField(default='0', null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Persil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_persil', models.CharField(max_length=255, null=True)),
                ('nomor_pelanggan', models.CharField(max_length=255, null=True)),
                ('modify_by', models.CharField(max_length=255, null=True)),
                ('modify_date', models.DateTimeField()),
                ('keterangan', models.CharField(max_length=255, null=True)),
                ('sys_id', models.IntegerField()),
                ('flag', models.IntegerField(default='0', null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
